### ISSUE TITLE
ResNet readout_zero_init=True?

### ISSUE THREAD

**Issue by D-X-Y** [microsoft/mup#13]
Dear Greg,

Awesome project! May I ask why the [linear output layer in ResNet](https://github.com/microsoft/mup/blob/main/examples/ResNet/resnet.py#L105) is initialized as 0 instead of Gaussian(mean=0, var=1) as mentioned in the paper?

Thanks a lot for your time and help.

**Comment by thegregyang** [comment]
Thanks @D-X-Y!

We discuss this in the paper in Section D.2.

![image](https://user-images.githubusercontent.com/53244851/167528061-7f4e1a12-3607-4c4b-9983-fbd530fca4ed.png)

Let us know if you have any question after reading this.

**Comment by D-X-Y** [comment]
Thanks a lot for your explaination!
