### ISSUE TITLE
missing os import in mup/examples/MLP/main.py ?

### ISSUE THREAD

**Issue by james-simon** [microsoft/mup#19]
Just thought I'd let you know that, when I ran `python mup/examples/MLP/main.py --load_base_shapes ./mup/examples/MLP/width64.bsh`, I got an error at the very bottom (when saving the `.tsv`) because `os` wasn't imported (losing a few hours of runtime!). Adding `import os` to the header fixed that. Maybe I was doing something wrong, but thought I'd flag it just in case

**Comment by edwardjhu** [comment]
This looks like an oversight on our end. Thanks for flagging!!
