### ISSUE TITLE
interpreting coord checks

### ISSUE THREAD

**Issue by llucid-97** [microsoft/mup#42]
Hi there, I'm working on a flax port of this and I'm trying to use the coord check scripts on a variant of your MLP example to see if I've done it right. I'm struggling to interpret the results though:

![sp_mlp_sgd_coord](https://user-images.githubusercontent.com/24926360/230602697-cedf50c7-1215-43d3-b041-6cf5c6b5c446.png)
![μp_mlp_sgd_coord](https://user-images.githubusercontent.com/24926360/230602699-8a9336cc-c60e-4d5c-9405-a850c50da65b.png)

The point I'm confused on is the green line in the muP graph step 1: if I understood your paper correctly, this should be a flat line right?
Looking through my code, i can't spot the mistake though, so I must ask, is my assumption about step 1 of the coord check wrong?

**Comment by edwardjhu** [comment]
Hi! Does the green curve correspond to the last layer? If so, this is expected. It is for a related reason that we recommend initializing the last layer weights to zero.

**Comment by llucid-97** [comment]
Aah I see. Yes it is for the last layer. Thanks
