### ISSUE TITLE
Interpreting jitter in coordcheck

### ISSUE THREAD

**Issue by leenachennuru** [microsoft/mup#58]
Hi, 

I have coord check plots with mup that look roughly stable but are a bit more jittery compared to the example plots. I was wondering if this can be considered expected behavior.

![mup_test](https://github.com/microsoft/mup/assets/5583850/59031636-20bd-4b09-ab63-9773a8967308)

Thanks!

**Comment by edwardjhu** [comment]
It's good as long as the magnitude is stable. One way to verify further is to extend the x-axis to the right

**Comment by leenachennuru** [comment]
Thanks! I could verify the stability of LR with width even with this jitter. Closing this issue accordingly.
