### ISSUE TITLE
How to use 'attn_mult' config

### ISSUE THREAD

**Issue by JiayiFeng** [microsoft/mup#8]
Hi, thanks for your amazing work!

In the example of using mup in GPT-2: https://github.com/microsoft/mutransformers/tree/main/mutransformers/models/gpt2, I notice that you changed attention scores from `kq / sqrt(d)` to `kq * attn_mult / d`, where `attn_mult` 
 is a new added config (https://github.com/microsoft/mutransformers/blob/main/mutransformers/models/gpt2/modeling_gpt2.py#L205). However, the default value of `attn_mult` is `sqrt(d)` (https://github.com/microsoft/mutransformers/blob/main/mutransformers/models/gpt2/configuration_gpt2.py#L199), which makes attention scores back to `kq / sqrt(d)`.

So why do we need this `attn_mult`? How should I set its value?

Thanks!

**Comment by thegregyang** [comment]
Feel free to open this back up if you have more questions.
